apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cicd
  name: ccp-cicd-secrets-reader
rules:
- apiGroups: [""]
  resources: ["secrets", "serviceaccounts"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ccp-custom-cluster-reader
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes", "namespaces"]
    verbs: ["get", "list"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ccp-custom-ns-reader
rules:
  - apiGroups: [""]
    resources: ["configmaps", "endpoints", "limitranges", "persistentvolumeclaims", "pods", "podtemplates", "replicationcontrollers", "resourcequotas", "secrets", "services", "events"]
    verbs: ["get", "list"]

  - apiGroups: ["apps"]
    resources: ["controllerrevisions", "daemonsets", "deployments", "replicasets", "statefulsets"]
    verbs: ["get", "list"]

  - apiGroups: ["authorization.k8s.io"]
    resources: ["localsubjectaccessreviews"]
    verbs: ["get", "list"]  

  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["get", "list"]

  - apiGroups: ["crd.projectcalico.org", "networking.k8s.io", "extensions"]
    resources: ["networkpolicies", "networksets", "ingresses"]
    verbs: ["get", "list"]

  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]

  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list"]

  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ccp-custom-cluster-writer
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["*"]
    
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ccp-custom-ns-writer
rules:
  - apiGroups: [""]
    resources: ["bindings", "configmaps", "endpoints", "limitranges", "persistentvolumeclaims", "pods", "podtemplates", "replicationcontrollers", "resourcequotas", "secrets", "services"]
    verbs: ["*"]
    
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["apps"]
    resources: ["controllerrevisions", "daemonsets", "deployments", "replicasets", "statefulsets"]
    verbs: ["*"]

  - apiGroups: ["authorization.k8s.io"]
    resources: ["localsubjectaccessreviews"]
    verbs: ["create"]  

  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["*"]

  - apiGroups: ["crd.projectcalico.org", "networking.k8s.io", "extensions"]
    resources: ["networkpolicies", "networksets", "ingresses"]
    verbs: ["*"]

  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["*"]

  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["*"]
  
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["*"]
