apiVersion: batch/v1
kind: Job
metadata:
  name: kube-hunter
spec:
  activeDeadlineSeconds: 300
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: kube-hunter
          image: aquasec/kube-hunter:0.6.3
          command: ["kube-hunter"]
          args: ["--pod", "--report=json", "--quick"]
      restartPolicy: Never
  backoffLimit: 4