kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ccp-custom-reader-rolebinding
  namespace: app-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ccp-custom-ns-reader
subjects:
- kind: Group
  namespace: app-ns
  name: azureGroupId