kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ccp-custom-writer-rolebinding
  namespace: app-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ccp-custom-ns-writer
subjects:
- kind: Group
  namespace: app-ns
  name: azureGroupId
- kind: ServiceAccount
  namespace: cicd
  name: sa-cicd